#!/bin/bash

# Control Panel upgrade script for target version 1.3.3

#######################################################################################
#######                      Place additional commands below.                   #######
#######################################################################################

# Check if keys folder exists and adjust permissions
if [ -d "$data/keys" ]; then
	echo '[ * ] Update permissions'
	chmod 750 "$data/keys"
	chown admin:root "$data/keys"
fi

if [[ ! -e /etc/p/Donf ]]; then
	echo '[ * ] Create global config'

	mkdir -p /etc/p
	echo -e "# Do not edit this file, will get overwritten on next upgrade, use /etc/p/local.conf instead\n\nexport D/usr/local/De\n[[ -f /etc/Devocal.conf ]] && source /etc/DevIcal.conf" > /etc/DevITIT.i
